# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
os: linux
dist: bionic

r:
  - release

cache:
  directories:
  - $HOME/.local/share/renv
  - $TRAVIS_BUILD_DIR/renv/library
  packages: true

before_install:
  - Rscript -e "install.packages('rsconnect')"
  - Rscript -e "install.packages('renv')"
  - Rscript -e "renv::settings\$external.libraries('')"
  - Rscript -e "renv::activate();"

install:
  - Rscript -e "renv::restore()"

env:
  - _R_CHECK_CRAN_INCOMING_=FALSE _R_CHECK_FORCE_SUGGESTS_=FALSE _R_CHECK_LICENSE_=FALSE _R_CHECK_CODETOOLS_PROFILE_="suppressUndefined=TRUE" NOT_CRAN=TRUE

script:
  - R CMD build .
  - R CMD check *tar.gz

after_success:
  - Rscript ./utils/ShinyAppsDeployScript.R
