on:
  workflow_dispatch

name: Deploy-shinyapps

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Deploy

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: 'x64'

      - name: Install yarn2
        run: |
          npm install -g yarn
          yarn set version berry
        working-directory: Client

      - name: Build UI
        run: |
          yarn install
          yarn build
        working-directory: Client

      - uses: r-lib/actions/setup-r@v1

      - name: Install R system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install rsconnect R package
        run: |
          install.packages('rsconnect')
        shell: Rscript {0}
        working-directory: Server

      - name: Deploy
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript utils/ShinyAppsDeployScript.R
        working-directory: Server
