on:
  workflow_dispatch

name: Deploy-shinyapps

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Deploy

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: Server/inst/app/

      - uses: r-lib/actions/setup-r@v1

      - name: Install system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev
        working-directory: Server

      - name: Install R development packages
        run: |
          install.packages('rsconnect')
        shell: Rscript {0}
        working-directory: Server
