on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: Deploy-shinyapps

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Deploy

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1

      - name: Install R development packages
        run: |
          install.packages('rsconnect')
        shell: Rscript {0}
        working-directory: Server
