on:
  push:
    branches:
      - master
      - migrant

name: Deploy to ShinyApps

jobs:
  Deploy:
    runs-on: ubuntu-20.04

    name: Deploy to ShinyApps

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - run: echo 'Print all environment variables'
      - run: env

      - name: Set up Node 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          architecture: 'x64'
          cache: 'yarn'
          cache-dependency-path: 'Client/yarn.lock'

      - name: Install yarn2
        run: |
          npm install -g yarn
          yarn set version latest
        working-directory: Client

      - name: Build UI
        run: |
          yarn install
          yarn build
        working-directory: Client

      - uses: r-lib/actions/setup-r@v1

      - name: Install R system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R deployment packages
        run: |
          install.packages('rsconnect')
          install.packages('renv')
          install.packages('testthat')
        shell: Rscript {0}
        working-directory: Server

      - name: Cache production R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R production packages
        run: |
          renv::restore()
        shell: Rscript {0}
        working-directory: Server

      - name: Deploy
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
          SHINYAPPS_APP_NAME: hivPlatform-${{ env.GITHUB_REF_NAME }}
        run: >
          rsconnect::setAccountInfo(
            name   = Sys.getenv('SHINYAPPS_ACCOUNT'),
            token  = Sys.getenv('SHINYAPPS_TOKEN'),
            secret = Sys.getenv('SHINYAPPS_SECRET')
          );
          rsconnect::deployApp(
            account = Sys.getenv('SHINYAPPS_ACCOUNT'),
            appName = 'hivPlatform-migrant',
            appFiles = c('app.R', 'DESCRIPTION', 'LICENSE', 'NAMESPACE', 'R/', 'man/', 'inst/', 'data/'),
            contentCategory = 'application',
            forceUpdate = TRUE
          )
        shell: Rscript {0}
        working-directory: Server
