on:
  workflow_dispatch

name: Deploy

jobs:
  deploy:
    runs-on: ubuntu-20.04

    name: Deploy application

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          architecture: 'x64'

      - name: Install yarn2
        run: |
          npm install -g yarn
          yarn set version berry
        working-directory: Client

      - name: Build UI
        run: |
          yarn install
          yarn build
        working-directory: Client

      - uses: r-lib/actions/setup-r@v1

      - name: Install R system dependencies
        run: |
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install R deployment packages
        run: |
          install.packages('rsconnect')
          install.packages('renv')
        shell: Rscript {0}
        working-directory: Server

      - name: Setup Linux R cache
        uses: actions/cache@v2
        with:
          path: ~/.local/share/renv
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-

      - name: Install R production packages
        run: |
          renv::restore()
        shell: Rscript {0}
        working-directory: Server

      - name: Deploy
        env:
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          Rscript utils/ShinyAppsDeployScript.R
        working-directory: Server
