on:
  push:
    paths:
    - 'Client/**'

name: UI-Node-build

jobs:
  build:
    runs-on: ubuntu-20.04

    name: Node sample

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node 14
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        architecture: 'x64'

    - name: Install yarn2
      run: |
        npm install -g yarn
        yarn set version berry
      working-directory: Client

    - name: Build UI
      run: |
        yarn install
        yarn build
      working-directory: Client

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: build-upload
        path: Client/build
